### ISSUE TITLE
Implement full OSW/VPE api

### ISSUE THREAD

**Issue by marcobox** [marcobox/ttnmakerissue#4]
*Feature Needed:*

- [X] Parse HSRP Data #7
- [X] Parse Show IP Route Data (with support for different VRF) #8 
- [X] Implement show vlan #9 
- [X] Parse Show interface Status #10  
- [X] Parse Show interface Description #11 
- [X] Short Name interface class and integration #16
- [X] Parse show inventory #22 

*Optional*
- [X] Implement check of OSPF conf #12 
- Show vrf brief functionality #17 (Won't Fix)
