### ISSUE TITLE
Implement Database Routine

### ISSUE THREAD

**Issue by marcobox** [marcobox/ttnmakerissue#5]
Issue do describe the need to get access to IP Tool Database to make query

_Requirement:_
- [X] connect to database #13 
- [X] connect to test database #25 
- [X] Implement check vlan #19 
- [X] Implement get free port #18 
- [X] Implement check vrf for vpe #26 
- [X] Implement check IP address and pool #34 
- [ ] Connect to test database #25 
- [ ] Implement insert vlan and Host #36 
- [ ] Implement  delete vlan #63
